### PR TITLE
fix: CORS config

### PR DESCRIPTION
**Pull request by fredericojordan**
## Description:

Adds these parameters to `settings.py`:

- `CORS_ORIGIN_ALLOW_ALL`: default = `False`
- `CORS_ORIGIN_WHITELIST`: default = `localhost,127.0.0.1`
  - Not set if `CORS_ORIGIN_ALLOW_ALL` is `True`

### CODE REVIEW

**Review by rkpinheiro — APPROVED** [review]

**Review by gustavuka — APPROVED** [review]

**Review by matpfernandes — APPROVED** [review]

**Review by natamvo — APPROVED** [review]

**Comment by natamvo** [comment]
@fredericojordan update the README

**Comment by fredericojordan** [comment]
> @fredericojordan update the README

@natamvo Update with what, exactly?
We are only listing CircleCI ENV vars in the README

**Comment by natamvo** [comment]
my bad, I thought was all envs, what do you think just a reminder of update/copy from .env.example (btw remove the `local` from name)?

**Review by rodolfolottin — APPROVED** [review]

**Review by gustavuka — APPROVED** [review]

**Comment by fredericojordan** [comment]
> my bad, I thought was all envs, what do you think just a reminder of update/copy from .env.example (btw remove the local from name)?

The `local` in the name suggests the file lists env vars examples that should work locally.

And that raises another question, should it have the minimum amount of variables needed or should we inform as much as possible?
In this particular example, both `CORS_ORIGIN_ALLOW_ALL` and `CORS_ORIGIN_WHITELIST` are optional, should I include them?

**Pull request merged**
