### PR TITLE
Feat: Add initial project Makefile

### PR DESCRIPTION
**Pull request by benmezger**
----

This adds a basic `Makefile` to the project. It handles the following targes:

- `tests`
- `clean`
- `run`
- `docker-up` -> with custom args
- `install-req` -> install base requirements
- `install-dev-req` -> install dev requirements
- `install-python` -> Check if required binaries exist and install Python

### CODE REVIEW

**Review by fredericojordan — APPROVED** [review]
🔝

**Review by rkpinheiro — APPROVED** [review]
🚀

**Review by matpfernandes — APPROVED** [review]

**Comment by phsetti** [comment]
Is copying `local.example.env` as `local.env` if doesn't exist, reasonable on `run`/`docker-up` ? 
Missing README changes. 
🚀

**Review by phsetti — APPROVED** [review]

**Review by karranb — APPROVED** [review]
🔝

**Review by fredericojordan — APPROVED** [review]

**Review by gustavuka — APPROVED** [review]

**Review by rodolfolottin — APPROVED** [review]

**Review by natamvo — APPROVED** [review]

**Pull request merged**
